### ISSUE TITLE
Compatibility problem with Krastorio rare metals

### ISSUE THREAD

**Issue by coding-komek** [MarcasRealAccount/FactorioDustlessMiners#2]
Hey,

sorry to bother again, but we have found another error that is thrown when you hook up a dustless miner that is supposed to mine rare metals from the Krastorio mod. When power and the required fluid is applied, the game then errors with the following message:
![rare-metals-error](https://user-images.githubusercontent.com/35131476/92404256-60ed1e00-f133-11ea-8c35-5cb2a5850978.PNG)

This problem does not exist with uranium, which also requires a separate fluid for mining.

**Comment by MarcasRealAccount** [comment]
Does this ore have multiple outputs?

**Comment by MarcasRealAccount** [comment]
Fixed the issue, though I wan't to duplicate the ore for the dustcloud and dust so that coal dust would have a fuel value :)

**Comment by coding-komek** [comment]
Well, that was quick. :)

**Comment by MarcasRealAccount** [comment]
Update should be live in a few minutes on factorio, though you can still download it here on github :)

**Comment by coding-komek** [comment]
Did a small test and it works.
Closing this issue as well then.
Thanks for the quick fix. :)
